apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
  namespace: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrydxn3984.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development        

---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
  namespace: api  
spec:
  ports:
  - name: poi
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: poi
  type: LoadBalancer