apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
  namespace: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrydxn3984.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: sqlserverdxn3984.database.windows.net
        - name: ASPNETCORE_ENVIRONMENT
          value: Development        
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: password


---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
  namespace: api  
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: poi
  type: LoadBalancer