apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
  namespace: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrydxn3984.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development        
        volumeMounts:
        - name: secrets-store-api-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-api-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-hack3-secretprovider"  
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  labels:
    app: poi
  namespace: api  
spec:
  ports:
  - name: poi
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: poi
  type: LoadBalancer