apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-hack3-secretprovider
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               
    keyvaultName: hack5      
    cloudName: ""                        
    objects:  |
      array:
        - |
          objectName: SQLPASSWORD
          objectType: secret             
          objectVersion: ""              
        - |
          objectName: SQLSERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLUSER
          objectType: secret
          objectVersion: ""  
    tenantId: 317611c7-646f-4d80-a168-3703b7a61d7b                