apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-hack3-secretprovider
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"    # Set to true for using managed identity
    userAssignedIdentityID: "684ea272-63e9-439f-a9f4-622829b25b0f"               
    keyvaultName: hack5      
    cloudName: ""                        
    objects:  |
      array:
        - |
          objectName: SQLPASSWORD
          objectType: secret             
          objectVersion: ""              
        - |
          objectName: SQLSERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLUSER
          objectType: secret
          objectVersion: ""  
    tenantId: 317611c7-646f-4d80-a168-3703b7a61d7b                