apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  labels:
    app: tripviewer
  namespace: azurehacker6003
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrydxn3984.azurecr.io/tripviewer/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile:80"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips:80"        


---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  labels:
    app: tripviewer
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: tripviewer
  type: LoadBalancer