apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-javaapp
  namespace: azurehacker6003
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: user-javaapp
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: 
        image: registrydxn3984.azurecr.io/tripinsights/user-java:1.0
        env:
        - name: SQL_SERVER
          value: sqlserverdxn3984
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: username
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: password