---
apiVersion: v1
kind: Namespace
metadata:
  name: tripinsights_team3_hacker06
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips_deploy
  labels:
    app: trips_deploy
  namespace: tripinsights_team3_hacker06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: 
        image: registrydxn3984.azurecr.io/tripinsights/trips:1.0
        env:
        -name: SQL_PASSWORD
          value: "mL9ii7Zj7"
        - name: SQL_SERVER
          value: "sqlserverdxn3984"
        - name: SQL_USER
          value: "sqladmindXn3984"
        - name: DOCS_URI
          value: "http://temp"
